# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testFRW' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testFRW

  target 'testFRWTests' do
    inherit! :search_paths
    # Pods for testing

pod 'testFRW', :path => '../testFRW'

  end

end

target 'testFRWExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testFRWExample

pod 'testFRW', :path => '../testFRW'


end
